# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: 755b149e-fdd4-4f9a-9622-84361a10dad4
  namespace: 755b149e-fdd4-4f9a-9622-84361a10dad4
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: 755b149e-fdd4-4f9a-9622-84361a10dad4
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "755b149e-fdd4-4f9a-9622-84361a10dad4-control-plane"
