# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 755b149e-fdd4-4f9a-9622-84361a10dad4-capi-aws-check
  namespace: 755b149e-fdd4-4f9a-9622-84361a10dad4
spec:
  template:
    metadata:
      name: 755b149e-fdd4-4f9a-9622-84361a10dad4-capi-aws
    spec:
      serviceAccountName: 755b149e-fdd4-4f9a-9622-84361a10dad4-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 755b149e-fdd4-4f9a-9622-84361a10dad4
        - 755b149e-fdd4-4f9a-9622-84361a10dad4
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 755b149e-fdd4-4f9a-9622-84361a10dad4-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
